version: '3'

services:
    spark-master:
        image: spark
        command: /spark/bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
        hostname: spark-master
        environment:
          SPARK_MASTER: spark://spark-master:7077
        expose:
          - 8080
          - 7077
          - 6066
        ports:
          - 7077:7077
          - 8080:8080
        volumes:
          - ./data:/data/

    spark-worker-1:
        image: spark
        depends_on:
          - spark-master
        command: /spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
        hostname: spark-worker-1
        environment:
          SPARK_MASTER: spark://spark-master:7077
          SPARK_WORKER_CORES: 1
          SPARK_WORKER_MEMORY: 1g
          SPARK_WORKER_PORT: 8881
          SPARK_WORKER_WEBUI_PORT: 8081
        links:
          - spark-master
        expose:
          - 8881
        ports:
          - 8081:8081
        volumes:
          - ./data:/data/

    spark-worker-2:
        image: spark
        depends_on:
          - spark-master
        command: /spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
        hostname: spark-worker-2
        environment:
          SPARK_MASTER: spark://spark-master:7077
          SPARK_WORKER_CORES: 1
          SPARK_WORKER_MEMORY: 1g
          SPARK_WORKER_PORT: 8881
          SPARK_WORKER_WEBUI_PORT: 8081
        links:
          - spark-master
        expose:
          - 8881
        ports:
          - 8082:8081
        volumes:
          - ./data:/data/


#TODO: gerar logs em um volume
